name: Release

on:
  push:
    branches: 
      - master
    tags: 
      - v*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      if: env.HEAD_TAG != '' 
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      if: env.HEAD_TAG != '' 
      with:
        java-version: 1.8
    - name: Build with Gradle and publish to Bintray
      if: env.HEAD_TAG != '' 
      run: ./gradlew bintrayPublish
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      if: env.HEAD_TAG != '' 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Please, check the [CHANGELOG](https://github.com/GameModsBR/NBT-Manipulator/blob/master/CHANGELOG.md) file for details.
        draft: false
        prerelease: false
    - name: Update the documentation
      if: env.HEAD_TAG != '' 
      run: ./gradlew gitPublishPush
